### ISSUE TITLE
do not create an update when nothing is changed

### ISSUE THREAD

**Issue by bkbartk** [richard-scott/cloud#1]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/ludeeus/integration_blueprint/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

a new version of this cloud hider is automatically released after every update of HA.
this means after updating HA I need to update cloud hider as well.

### Describe the solution you'd like

Is it possible to create a check if anything has been changed in defaulf-config and if not, just not create a new release?

### Describe alternatives you've considered

installing the updates

### Additional context

I need to reboot HA more.

**Comment by richard-scott** [comment]
Fixed with https://github.com/richard-scott/cloud/commit/e4130634e56fbd21bd302c9b100dc7c72a9dfeeb

**Comment by richard-scott** [comment]
I'm re-opening this as the change I made doesn't work as there are always differences between what we have now (as we've modified the codebase) and what upstream provides. This will require more thought.

**Comment by richard-scott** [comment]
I've added some checks for upstream changes in [commit](https://github.com/richard-scott/cloud/commit/b64d1592f9f63859d7be1681eaad8844cc088c56). I'll keep this open incase that doesn't work as expected.

**Comment by richard-scott** [comment]
I'm archiving this repo as I can't find a nice way to only update files when no changes are made. I'm going to use [this](https://github.com/richard-scott/homeassistant-mostly_default_config) instead which I forked from here:

https://github.com/abjugard/homeassistant-mostly_default_config
